keybinds:
  bindings: {}
resourcePack:
  name: "Default Pack"
  path: "resourcepacks/default"
  description: "Pack shipped with MineGDX."
  sizeMod: 1.0
servers:
  "hmm": "ok"
  "local": "127.0.0.1"
playerName: "ellie"
clientUUID: 1549027659761